schemaVersion: 2.2.0
components:
  - name: Pac-Wall
    attributes:
      gl/inject-editor: true
    container:
      image: Dockerfile
      env:
        - name: STORYBOOK_HOST
          value: "0.0.0.0"
      endpoints:
        - name: storybook
          targetPort: 9001
          secure: true
          protocol: http
